apiVersion: v1
kind: ServiceAccount
metadata:
  name: ids-admin-api
  namespace: identity-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ids-sts
  namespace: identity-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-secret-reader
  namespace: identity-platform
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-secret-reader-admin-api
  namespace: identity-platform
subjects:
  - kind: ServiceAccount
    name: ids-admin-api
    namespace: identity-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-secret-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-secret-reader-sts
  namespace: identity-platform
subjects:
  - kind: ServiceAccount
    name: ids-sts
    namespace: identity-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-secret-reader
